---
title: "Modèles mixtes"
subtitle: "TP1.3: `Orange`"
author: "Florent Chuffart"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---


```{r, echo=FALSE, eval=TRUE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo=TRUE, results="verbatim", warning=FALSE)
```
# Data

J’étudie le jeu de données suivant : 

```{r, eval=TRUE, echo=TRUE, results="verbatim"}
d = datasets::Orange
d$Tree = factor(d$Tree, levels=unique(d$Tree), order=FALSE)
head(d)
dim(d)

d2 = d
# Adding biais on Tree 2 circumference dispersion values
tmp_circ = d2[d2$Tree%in%2, ]$circumference
tmp_age = d2[d2$Tree%in%2, ]$age
set.seed(1)
m = lm(tmp_circ~tmp_age)
new_circ = tmp_circ + 3*m$residuals
layout(matrix(1:2,1), respect=TRUE)
plot(tmp_age, tmp_circ, col=2, ylim=range(c(tmp_circ, new_circ)))
abline(m, col=2)
points(tmp_age, new_circ, col=4)
abline(lm(new_circ~tmp_age), col=4, lty=2)
d2[d2$Tree%in%2, ]$circumference = new_circ


layout(matrix(1:2,1), respect=TRUE)
plot(density(d$circ))
plot(density(d2$circ))

layout(matrix(1:2,1), respect=TRUE)
plot(circumference~age, d, pch=16, col=d2$Tree)
plot(circumference~age, d2, pch=16, col=d2$Tree)

d = d2


```



# Modèles

## Modèles lineaires classiques

Je construis les modèles suivants : 

```{r}
m2 = lm(circumference~age*Tree, d)
```



## `m2`
```{r echo=FALSE, results="verbatim"}
m2 = lm(circumference~age*Tree, d)
summary(m2)
layout(matrix(1:2, 1, byrow=TRUE), respect=TRUE)
plot(circumference~age, d, pch=16, col=d$Tree)
abline(a=m2$coef[1]             , b=m2$coef[2]              , col=1)
n = length(levels(d$Tree))
for (i in 2:n) {
  abline(a=m2$coef[1] + m2$coef[i+1], b=m2$coef[2] + m2$coef[n+i] , col=i)
}
legend("bottomright", cex=.7, levels(d$Tree), col=1:length(levels(d$Tree)), pch=16)
```



## Modèles mixtes

Je construis les modèles suivants : 

```{r}
m8 = lme4::lmer(circumference ~ age + (0+age | Tree), data = d)
```


```{r}
layout(1, respect=TRUE)
m8 = lme4::lmer(circumference ~ age + (0+age | Tree), data = d)
summary(m8)
coef(m8)
plot(circumference~age, d, pch=16, col=d$Tree)
abline(a=coef(m8)$Tree[1,1], b=coef(m8)$Tree[1,2], col=1)
abline(a=coef(m8)$Tree[2,1], b=coef(m8)$Tree[2,2], col=2)
abline(a=coef(m8)$Tree[3,1], b=coef(m8)$Tree[3,2], col=3)
abline(a=coef(m8)$Tree[4,1], b=coef(m8)$Tree[4,2], col=4)
abline(a=coef(m8)$Tree[5,1], b=coef(m8)$Tree[5,2], col=5)
```




## Choix de modèles



```{r echo=FALSE, results="verbatim"}
layout(matrix(1:2, 1, byrow=TRUE), respect=TRUE)
plot(circumference~age, d, pch=16, col=d$Tree, ylim=c(0,250))
abline(a=m2$coef[1]             , b=m2$coef[2]              , col=1)
n = length(levels(d$Tree))
for (i in 2:n) {
  abline(a=m2$coef[1] + m2$coef[i+1], b=m2$coef[2] + m2$coef[n+i] , col=i)
}
legend("bottomright", cex=.7, levels(d$Tree), col=1:length(levels(d$Tree)), pch=16)

plot(circumference~age, d, pch=16, col=d$Tree, ylim=c(0,250))
abline(a=coef(m8)$Tree[1,1], b=coef(m8)$Tree[1,2], col=1)
abline(a=coef(m8)$Tree[2,1], b=coef(m8)$Tree[2,2], col=2)
abline(a=coef(m8)$Tree[3,1], b=coef(m8)$Tree[3,2], col=3)
abline(a=coef(m8)$Tree[4,1], b=coef(m8)$Tree[4,2], col=4)
abline(a=coef(m8)$Tree[5,1], b=coef(m8)$Tree[5,2], col=5)
```


```{r echo=FALSE}
plot(c(
  BICm2=BIC(m2),
  BICm8=BIC(m8)
))
```
```{r}
BIC(m2)
BIC(m8)
```


# Session Information

```{r results="verbatim"}
sessionInfo()
```

